services:
  openhab:
    image: "openhab/openhab:latest-alpine"
    container_name: openhab
    restart: always
    # network_mode: host # required for UPnP discovery
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./openhab/addons:/openhab/addons"
      - "./openhab/conf:/openhab/conf"
      - "./openhab/userdata:/openhab/userdata"
    environment:
      CRYPTO_POLICY: "unlimited"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Helsinki"
      USER_ID: "$USER_ID"
      GROUP_ID: "$GROUP_ID"
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
    ports:
      - 8080:8080
      - 8443:8443

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    volumes:
      - "./mosquitto:/mosquitto"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    ports:
      - 1883:1883
      # - 9001:9001 # for websocket communication
